// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUdaJSYPVy37GFzD5Al2wlKfDRKdaTRN4',
    appId: '1:688009382588:web:aba4134426075a70af1eb9',
    messagingSenderId: '688009382588',
    projectId: 'aestheticpass-818c6',
    authDomain: 'aestheticpass-818c6.firebaseapp.com',
    storageBucket: 'aestheticpass-818c6.firebasestorage.app',
    measurementId: 'G-BN06X81GZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTErwRNl39dZ7DHev7TvoxSq4RQ8Jjs1I',
    appId: '1:688009382588:android:f974b7bf69048d2eaf1eb9',
    messagingSenderId: '688009382588',
    projectId: 'aestheticpass-818c6',
    storageBucket: 'aestheticpass-818c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7mqKnoWVAAwbp0kUmky5mFTYjNakPnxU',
    appId: '1:688009382588:ios:ef539e72aa29a28caf1eb9',
    messagingSenderId: '688009382588',
    projectId: 'aestheticpass-818c6',
    storageBucket: 'aestheticpass-818c6.firebasestorage.app',
    iosClientId: '688009382588-3l9cm1vje1dlglmf11ej5h92m4gprb2i.apps.googleusercontent.com',
    iosBundleId: 'com.svapps.aestheticpass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7mqKnoWVAAwbp0kUmky5mFTYjNakPnxU',
    appId: '1:688009382588:ios:d41175cabcdd0db4af1eb9',
    messagingSenderId: '688009382588',
    projectId: 'aestheticpass-818c6',
    storageBucket: 'aestheticpass-818c6.firebasestorage.app',
    iosClientId: '688009382588-9v0o9r1dafahqkkomp9780unu7b02nae.apps.googleusercontent.com',
    iosBundleId: 'com.glowpass.glowpass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUdaJSYPVy37GFzD5Al2wlKfDRKdaTRN4',
    appId: '1:688009382588:web:b9b2696fcded7d3caf1eb9',
    messagingSenderId: '688009382588',
    projectId: 'aestheticpass-818c6',
    authDomain: 'aestheticpass-818c6.firebaseapp.com',
    storageBucket: 'aestheticpass-818c6.firebasestorage.app',
    measurementId: 'G-JMN6NL9G7E',
  );
}
